/*
 * This file is generated by jOOQ.
 */
package com.rita.wxx.po.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonPo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private Integer age;
    private Integer sex;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public PersonPo() {}

    public PersonPo(PersonPo value) {
        this.id = value.id;
        this.name = value.name;
        this.age = value.age;
        this.sex = value.sex;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public PersonPo(
        Long id,
        String name,
        Integer age,
        Integer sex,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.sex = sex;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>wxx.person.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>wxx.person.id</code>.
     */
    public PersonPo setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>wxx.person.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>wxx.person.name</code>.
     */
    public PersonPo setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>wxx.person.age</code>.
     */
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>wxx.person.age</code>.
     */
    public PersonPo setAge(Integer age) {
        this.age = age;
        return this;
    }

    /**
     * Getter for <code>wxx.person.sex</code>. 0: male 1 female
     */
    public Integer getSex() {
        return this.sex;
    }

    /**
     * Setter for <code>wxx.person.sex</code>. 0: male 1 female
     */
    public PersonPo setSex(Integer sex) {
        this.sex = sex;
        return this;
    }

    /**
     * Getter for <code>wxx.person.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>wxx.person.create_time</code>.
     */
    public PersonPo setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * Getter for <code>wxx.person.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>wxx.person.update_time</code>.
     */
    public PersonPo setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PersonPo other = (PersonPo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.age == null) {
            if (other.age != null)
                return false;
        }
        else if (!this.age.equals(other.age))
            return false;
        if (this.sex == null) {
            if (other.sex != null)
                return false;
        }
        else if (!this.sex.equals(other.sex))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.age == null) ? 0 : this.age.hashCode());
        result = prime * result + ((this.sex == null) ? 0 : this.sex.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PersonPo (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(sex);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
