/*
 * This file is generated by jOOQ.
 */
package com.rita.wxx.po;


import com.rita.wxx.po.tables.Person;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in wxx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PERSON_NAME = Internal.createIndex(DSL.name("name"), Person.PERSON, new OrderField[] { Person.PERSON.NAME }, false);
}
