/*
 * This file is generated by jOOQ.
 */
package com.rita.wxx.po;


import com.rita.wxx.po.tables.Person;


/**
 * Convenience access to all tables in wxx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>wxx.person</code>.
     */
    public static final Person PERSON = Person.PERSON;
}
